# Generated by Django 4.2.17 on 2025-01-12 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(default=' ', max_length=12, unique=True, verbose_name='Номер телефона'),
            preserve_default=False,
        ),
    ]
